from samplebrowsesrc.dialogs.dbselect import *
from samplebrowsesrc.dialogs.settings import *
from samplebrowsesrc.dialogs.audiosettings import *
from samplebrowsesrc.dialogs.statistics import *
from samplebrowsesrc.dialogs.tagcolors import *
from samplebrowsesrc.dialogs.about import *
from samplebrowsesrc.dialogs.sampleimport import *
from samplebrowsesrc.dialogs.removesamples import *
from samplebrowsesrc.dialogs.addsampleswithtags import *
from samplebrowsesrc.dialogs.scanoptions import *
from samplebrowsesrc.dialogs.tagseditor import *
